### PR TITLE
feat: project details view

### LINKED ISSUE #50: Project Cards - Details View & Links
Thought we had links from project cards to the individual repositories in an open PR but seeing as there are currently no PRs open and no links on the cards on open.fiveable.me, I guess we still need that!

This issue can be separated into 2 separate PRs if desired:
- [ ] Add links to project preview cards so it's easy to visit each project repo.
- [ ] Add a details view for the project cards so it's easy to see a quick synopsis of the project without diving in. Submissions in the Google form should already have this information, so minimal work needed there to flow it into the site.

For the details view, I think this could be a great opportunity to experiment with animations or CSS tricks. A couple ideas:
- A slide-out dark background on hover with white text.
- A card-flip animation on hover. There's a free tutorial preview of this in this course: [Natours Project — Using Advanced CSS and Sass (Part 2)](https://www.udemy.com/course/advanced-css-and-sass/) ("Building the Tours Section - Part 1/2/3"). I'm sure there's also libraries out there to make this a piece of cake. 
- A pop-out modal or some kind of FLIP transformation on the card. See [react-flip-toolkit](https://github.com/aholachek/react-flip-toolkit) (personal favorite of mine— very powerful & very easy to use, at least depending on what you're doing). Tutorial for it [here](https://alex.holachek.com/rft-tutorial/#0).

### PR DESCRIPTION
**Pull request by exu3**
This PR adds a modal component for a details view on the project cards. Also, adds the latest projects submitted on the Google Form.

Making a draft PR because it doesn't have any animations yet.

Closes #50

### CODE REVIEW

**Review by sarthaktexas — DISMISSED** [review]

**Comment by awlevin** [comment]
UI looks great! UX-wise I think I'd like clicking the backdrop to also close the modal if that's possible. And the opening is pretty abrupt— I'd love if we could find a subtle CSS effect to make it feel a little smoother. 

Also, opening the hangman modal on mobile.. the UI is a little off. I think it's just because the description is long so maybe setting a maxHeight and vertical scroll on the description area would solve that. 
Screen Shot 2021-04-21 at 6 59 17 PM

**Comment by awlevin** [comment]
Question for the group— would it make sense to also use NextJS's router + browser history for opening and closing / 
navigating between project details views? I'm personally indifferent, might be more trouble than it's worth.

**Comment by exu3** [comment]
> would it make sense to also use NextJS's router + browser history for opening and closing /
navigating between project details views?

something like [this](https://github.com/vercel/next.js/tree/canary/examples/with-route-as-modal)? I think it could be a useful feature if there are a lot of projects on the page

**Comment by awlevin** [comment]
I think so! Maybe this is a P2 (priority 2 / phase 2— or otherwise lower priority) requirement of details views though, so we could get the initial feature released sooner?

**Review by sarthaktexas — APPROVED** [review]

**Review by sarthaktexas — APPROVED** [review]

**Comment by zaida04** [comment]
Can we add the 
> clicking the backdrop to also close the modal if that's possible

bit?

**Comment by exu3** [comment]
I couldn't figure it out because when I added the `onClick={() => setShowModal(false)}` to the background div, the modal would close when i clicked anywhere on the screen 🤔 

Any idea if there's a better way to do it?

**Comment by sarthaktexas** [comment]
> I couldn't figure it out because when I added the `onClick={() => setShowModal(false)}` to the background div, the modal would close when i clicked anywhere on the screen 🤔
> 
> Any idea if there's a better way to do it?

even with the z-index of the modal above it?

**Comment by sarthaktexas** [comment]
> UI looks great! UX-wise I think I'd like clicking the backdrop to also close the modal if that's possible. And the opening is pretty abrupt— I'd love if we could find a subtle CSS effect to make it feel a little smoother.
> 
> Also, opening the hangman modal on mobile.. the UI is a little off. I think it's just because the description is long so maybe setting a maxHeight and vertical scroll on the description area would solve that.
> Screen Shot 2021-04-21 at 6 59 17 PM

i can get on the css animation when @eilla1 finishes

**Comment by exu3** [comment]
yeah the modal is z-40 and the bg is z-50

**Comment by sarthaktexas** [comment]
Should be the opposite

**Review by zaida04 — APPROVED** [review]

**Comment by awlevin** [comment]
> > I couldn't figure it out because when I added the `onClick={() => setShowModal(false)}` to the background div, the modal would close when i clicked anywhere on the screen 🤔
> > Any idea if there's a better way to do it?
> 
> even with the z-index of the modal above it?

Might want to disable touch events on the div above it or onClick = {event => event.preventDefault} somewhere 🤷‍♂️

**Pull request merged**
