### PR TITLE
feat: contributor component

### LINKED ISSUE #20: Contributor component
create the contributor component in the components directory
Screenshot (15)

### PR DESCRIPTION
**Pull request by amal-san**
#20 feature implementation

### CODE REVIEW

**Comment by zaida04** [comment]
First off, this is an amazing contribution and thank you for tackling this! Some issues on mobile with responsiveness: 
4E7AC2B4-6CC7-42A6-8272-5E98EDDF6D62

Also confused on how it determines maintainer status considering Ella, Sarthak, Aaron, and me are all maintainer level in repo settings.

**Comment by amal-san** [comment]
I built this with respect to the this GitHub api https://api.github.com/repos/thinkfiveable/open/contributors .For now maintainer is found out by the index (who ever comes first will be the maintainer). Is there any way to provide info about who all are maintainers in the api. It will be helpful

will fix the mobile view 👍

**Comment by zaida04** [comment]
> I built this with respect to the this GitHub api [api.github.com/repos/thinkfiveable/open/contributors](https://api.github.com/repos/thinkfiveable/open/contributors) .For now maintainer is found out by the index (who ever comes first will be the maintainer). Is there any way to provide info about who all are maintainers in the api. It will be helpful
> 
> will fix the mobile view 👍

You can either hardcode the maintainers (me, Sarthak, Ella, and Aaron) or `GET https://api.github.com/orgs/thinkfiveable/public_members`, keep track of the usernames, and compare accordingly.

**Review by zaida04 — APPROVED** [review]

**Review by exu3 — CHANGES_REQUESTED** [review]
Hey @amal-san, First off, thanks for the PR! 

1. Rename `contributor.mdx` to `contributors.mdx` to stay consistent with the page title and footer. Also, I think you could just put the page in the `pages` directory instead of `docs`. 

2. The styling doesn't seem to match the Figma designs. I would recommend making it a 2 column layout on larger screens and 1 column on mobile and removing the gray background. See [design files](https://www.figma.com/file/AT1rNs6YZtkk7jjo5iWMZW/Fiveable-Open-Source-Landing?node-id=0%3A1). 
Screen Shot 2021-05-04 at 10 09 42 AM

**Comment by zaida04** [comment]
hotlinks to gh profiles on the contributor component please
`https://github.com/USERNAME`

**Comment by exu3** [comment]
in addition to the above comment, could you also enlarge the username text (or decrease the size of the image) so it's proportional?
Also, define a specific width so that the badge length so it doesn't span the full width on small screens. Ideally, the badge should be shorter than the width of the username.
Screen Shot 2021-05-05 at 10 22 09 AM

**Review by exu3 — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
