### PR TITLE
feat: add search page

### LINKED ISSUE #21: Card component
this is the second variant of the project card component
card component

### PR DESCRIPTION
**Pull request by jasonappah**
This PR adds components for the search bar and alternate project card, as well as a nonworking search page. It's not responsive for now but I can do that later today - I was having trouble with the breakpoints. Closes #21

### CODE REVIEW

**Comment by jasonappah** [comment]
There's some weird stuff going on with the images overflowing on mobile, but it's mostly responsive now. I have no idea why the images are being weird so I'd appreciate pointers on that. I thought I'd be good with just specifying `object-cover`.

**Review by zaida04 — CHANGES_REQUESTED** [review]
This PR needs to be updated with master.

Also, weird stuff going on with the images, was this what you were talking about?
image

**Comment by jasonappah** [comment]
Alright, the [search](https://open-git-fork-jasonappah-feat-search-card-thinkfiveable.vercel.app/search) page should be all good and fully responsive.

**Comment by zaida04** [comment]
Alright, can we have a button on the main page that'll open up this search bar? Preferably with a back button to return back to the home page. 

Also, need to update this to work with our actual prod data instead of test data.

**Comment by jasonappah** [comment]
Will do tonight.

**Comment by jasonappah** [comment]
Whoops I didn't mean to force push, my bad. Search works now though, using Fuse.js and I've added a search bar to the homepage which becomes a search button on smaller screen sizes.

**Review by zaida04 — APPROVED** [review]

**Review by exu3 — APPROVED** [review]
Nice work, thanks Jason! 🚀

**Pull request merged**
