### PR TITLE
Fix outline

### PR DESCRIPTION
**Pull request by nabesuke5098**
same issues when focusing elements:
search button
スクリーンショット 2021-05-02 13 48 15
search form search.js
スクリーンショット 2021-05-02 13 48 25
&back button backbtn.js
スクリーンショット 2021-05-02 13 48 31

### CODE REVIEW

**Review by zaida04 — APPROVED** [review]

**Comment by exu3** [comment]
hey @nabesuke5098, thanks for the PR! However, the focus outlines should be there for accessibility as a visible indication that you can type in a form field or click a button. If you'd like to get rid of the blue outlines, please open a new PR replacing them with something else. (perhaps increase the border radius to make it fit around the button/input better or make it dotted?)

Check out [this article](https://www.a11yproject.com/posts/2013-01-25-never-remove-css-outlines/) for more information if you're interested.

**Comment by ronaldleung1** [comment]
Just want to mention that I've already changed focus styles in #60 according to those accessibility specifications. Let me know what you think of them!

**Comment by nabesuke5098** [comment]
@eilla1 Thank you for your consideration. I got it!

**Comment by nabesuke5098** [comment]
I think it's nice that the button has no outline, because button has any onClick action, not onBlur! @googol88

**Comment by ronaldleung1** [comment]
Yeah, totally agree with you there @nabesuke5098! The default outline is pretty ugly in my opinion, regardless of the role it plays.

**Comment by nabesuke5098** [comment]
Yeah, I agree with you @googol88  it doesn't fit the design!

**Pull request closed without merging**
