### PR TITLE
docs:add instructions to run locally

### LINKED ISSUE #2: make readme clearer for how to locally deploy

### PR DESCRIPTION
**Pull request by exu3**

### CODE REVIEW

**Review by TejasCreative — DISMISSED** [review]

**Review by sarthaktexas — CHANGES_REQUESTED** [review]
let's remove the $ from the commands cause it makes it harder to copy and paste them

**Comment by zaida04** [comment]
For future reference, you can link a PR to an issue just by saying the words "closes #issuenumber"

**Comment by zaida04** [comment]
closes #2

**Comment by awlevin** [comment]
> For future reference, you can link a PR to an issue just by saying the words "closes #issuenumber"

one of my fave features 😄

**Comment by exu3** [comment]
Oh gotcha thanks for letting me know!

**Review by sarthaktexas — CHANGES_REQUESTED** [review]
for the cd command, it's just cd open which can be confusing. so for the git clone command put a folder parameter like fiveable-open so that in the cd command you can explicitly say cd fiveable-open. does that make sense? sorry i didn't say this in the last one it was like 4am

**Review by sarthaktexas — APPROVED** [review]
ehh couple formatting things bug me but that's just me being picky lol. approved

**Review by zaida04 — APPROVED** [review]

**Pull request merged**
