### PR TITLE
feat: about page

### LINKED ISSUE #33: Description of project / Learn more
The `Learn more` button on the homepage should link to another page `/about` to explain what the project is to new visitors to the site.

### PR DESCRIPTION
**Pull request by exu3**
created about page with more information and linked learn more button to this page

closes #33

### CODE REVIEW

**Review by sarthaktexas — CHANGES_REQUESTED** [review]
1. why are we using router
2. were using mdx for these simple pages, i wanted to discuss this before it was done

**Comment by exu3** [comment]
1. Not sure when to use link vs router vs a tag. Would `next/link` work better in this case?
2. 👍

**Comment by sarthaktexas** [comment]
yup use next link here, router is for SSR sites and a couple of other use cases

**Comment by awlevin** [comment]
@eilla1 this is awesome! You're a copywriting queen 👑 

I agree with @sarthaktexas that Next Link is probably better here. On the back button, I believe this will also solve the issue of the button not showing `cursor: pointer` during hover, which is a little awkward at the moment.

More importantly, seems like something is wonky on wider screens. The mouse doesn't go into `cursor: text` when hovering over the text lower on the page (again, I think it's only on wider screens), and adding `overflow: hidden` on the element with height of 15rem seems to fix it, but then awkwardly clips the SVG. Maybe the move is to make the SVG absolutely positioned inside of a relatively positioned div so it's removed from the flow of the page? And then maybe use z-index to get the text to overlay as desired? I'm sure there's a better approach than this, but those are a couple ideas off the top of my head 😄 

Screen Shot 2021-04-03 at 5 21 26 PM

**Comment by awlevin** [comment]
#### 📝Changed routes:


| [**/about**](https://open-7q8huix87-thinkfiveable.vercel.app/about) | [**/**](https://open-7q8huix87-thinkfiveable.vercel.app/) |
|:-:|:-:|
|<a href="https://open-7q8huix87-thinkfiveable.vercel.app/about">Screenshot of /about</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/R0DdbVDS8BYynruwVSKC_7Dxi0IA57pHtMqLdm9WEKv34PUV8GGBBZv4G-bBUXl2yBjt8vigNkYOBLTWmBhByg.png">(view full size)</a> |<a href="https://open-7q8huix87-thinkfiveable.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/HAyf6zeZ4m5HUbVCyDh6JndrLMDsqhqeaJgt4eKaZo9NJDxQS5dwLyS42VfPmGVDKPQrAUOT-l-R3zRSb-kVhA.png">(view full size)</a> |







Commit 7098a06eedb35e4e6552aee269a7adace23f5302 (https://open-7q8huix87-thinkfiveable.vercel.app).

**Review by sarthaktexas — CHANGES_REQUESTED** [review]
MDX but I want to peer-program it with you

**Pull request closed without merging**
