### PR TITLE
feat: dynamically fetch repository data via github api

### LINKED ISSUE #42: optimize the various data holders
We currently hard code the data for `./data/PROJECTS.json` and `./data/CONTRIBUTORS.json`. In the future, post MVP stage, I'd like to dynamically fetch this data, either from the Github API or our own proxy (probably overcomplicating this).

This is finally where the backend bois rise up.

### PR DESCRIPTION
**Pull request by rayhanadev**
Hello! After a fair bit of polishing I feel ready to open a pull request for this. Closes #42

---

This pull request adds two functions to query the Github APIs (Restful or GraphQL) to gather repository data. Either function takes in the owner's name and repository's name from `data/PROJECTS.json` and spits out data that is then filtered into friendly data for each modal. It's fairly barebones but can be expanded easily to accommodate your needs!

I also included an option that allows you to define a Github Personal Access Token under the `GITHUB_TOKEN` environment variable, but if you decide not to generate one then you should go with the Restful API for your queries (current setup).

Another notable mention is the GraphQL API has the ability to fetch open graph images which can replace the need to write out the repoLogo property in the JSON.

Lastly, you can drop projectDescription property since it is fetched via API. It's the only property that is completely covered via the API as of this PR.

Let me know what you think!

Edit:
@zaida04 requested what you will need in the JSON so...
...if you use the Restful Function, you will need:
- Repository Owner
- Repository Name
- Repository Logo/Image
- Project Type
- Award

...if you use the GraphQL Function, you will need:
- Repository Owner
- Repository Name
- Project Type
- Award

Edit:
One idea to replace projectType is to use the tags on a repository:
Pros:
- Saves space/store less data
- Variety/wider range of areas
- Multiple types

Cons:
- Too wide range of tags?

### CODE REVIEW

**Review by rayhanadev — COMMENTED** [review]
LGTM

**Comment by zaida04** [comment]
Can you make a quick list as to what existing properties/data we can replace typing manually with this PR?

**Comment by rayhanadev** [comment]
@zaida04 done!

**Review by zaida04 — APPROVED** [review]

**Review by exu3 — APPROVED** [review]
Thanks!

**Pull request merged**
